export const intervals = [
    "unisson",
    "seconde_mineure",
    "seconde_majeure",
    "tierce_mineure",
    "tierce_majeure",
    "quarte_juste",
    "quarte_aug/quinte_dim",
    "quinte_juste",
    "quinte_aug/sixte_mineure",
    "sixte_majeure/septieme_dim",
    "septieme_mineure",
    "septieme_majeure",
    "octave",
    "neuvieme_mineure",
];

export const buttons = [
    "Unisson",
    "Seconde mineure",
    "Seconde Majeure",
    "Tierce mineure",
    "Tierce Majeure",
    "Quarte juste",
    "Quarte aug&nbsp/ Quinte dim",
    "Quinte juste",
    "Quinte aug&nbsp/ Sixte mineure",
    "Sixte majeure&nbsp/ Septième dim",
    "Septième mineure",
    "Septième Majeure",
    "Octave",
    "Neuvième mineure",
];

export const buttonsMobile = [
    "Uniss.",
    "2<sup>nde</sup> m",
    "2nde M",
    "3<sup>ce</sup> m",
    "3<sup>ce</sup> M",
    "4<sup>te</sup>",
    "4<sup>te</sup> aug / 5<sup>te</sup> dim",
    "5<sup>te</sup>",
    "5<sup>te</sup> aug / 6<sup>te</sup> m",
    "6<sup>te</sup> M / 7<sup>ème</sup> dim",
    "7<sup>ème</sup> m",
    "7<sup>ème</sup> M",
    "8<sup>ve</sup>",
    "9<sup>ème</sup> m",
];

export const notes = [
    ["C"],
    ["C#", "Db"],
    ["D"],
    ["D#", "Eb"],
    ["E", "Fb"],
    ["F"],
    ["F#", "Gb"],
    ["G"],
    ["G#", "Ab"],
    ["A"],
    ["A#", "Bb"],
    ["B", "Cb"],
];
